#!/usr/bin/env bash

# set -eu -o pipefail
# shopt -s failglob

# Gradle Version
GRADLE_VER=7.5.1

export PATH=/opt/gradle-$GRADLE_VER/bin:$PATH

cp -r /autograder/submission/Greeter /autograder/source

# Copy un-altered test cases to env
rm -rf /autograder/source/Greeter/src/test
cp -rf /autograder/source/test /autograder/source/Greeter/src

cd /autograder/source/Greeter
rm -f results.json

gradle -Dtest.ignoreFailures=true -Dtest.failFast=false clean build

mv results.json /autograder/results
